In [3]:
import numpy as np
import pandas as pd

In [6]:
# Data generation and preparation
songStrings = np.array([
    #"CCGGAAGFFEEDDCGGFFEEDGGFFEEDCCGGAAGFFEEDDC",
    "ABCDEFGHIABCDEFGHIABCDEFGHIABCDEFGHIABCDEF"
    #"ABCDEFIGHABCDEFIGHABCDEFIGHABCDEFIGHABCDEF"
    #"AHCFEDGBIAHCFEDGBIAHCFEDGBIAHCFEDGBIAHCFED"
])

(21, 4) (21, 4)

In [4]:
import numpy as np
import pandas as pd

def generate_note_dataframe(songString):
    # Total rows needed
    total_rows = 42

    # Extract "note" and "next note" with proper wrapping
    notes = []
    next_notes = []

    for i in range(total_rows):
        # Calculate indices for the note and next note
        start_index = i % len(songString)
        end_index = (i + 4) % len(songString)
        next_note_index = (i + 4) % len(songString)

        # Check if the note wraps around the string end
        if end_index > start_index:
            note = songString[start_index:end_index]
        else:
            note = songString[start_index:] + songString[:end_index]

        # Next note is simply the character at the next_note_index
        next_note = songString[next_note_index]

        # Append to lists
        notes.append(note)
        next_notes.append(next_note)

    # Create DataFrame
    df = pd.DataFrame({
        "note": notes,
        "next note": next_notes
    })

    return df

In [16]:
# Example usage
songString_1 = "ABCDEFGHIABCDEFGHIABCDEFGHIABCDEFGHIABCDEF"
df_1 = generate_note_dataframe(songString_1)
print(df_1)

    note next note
0   ABCD         E
1   BCDE         F
2   CDEF         G
3   DEFG         H
4   EFGH         I
5   FGHI         A
6   GHIA         B
7   HIAB         C
8   IABC         D
9   ABCD         E
10  BCDE         F
11  CDEF         G
12  DEFG         H
13  EFGH         I
14  FGHI         A
15  GHIA         B
16  HIAB         C
17  IABC         D
18  ABCD         E
19  BCDE         F
20  CDEF         G
21  DEFG         H
22  EFGH         I
23  FGHI         A
24  GHIA         B
25  HIAB         C
26  IABC         D
27  ABCD         E
28  BCDE         F
29  CDEF         G
30  DEFG         H
31  EFGH         I
32  FGHI         A
33  GHIA         B
34  HIAB         C
35  IABC         D
36  ABCD         E
37  BCDE         F
38  CDEF         A
39  DEFA         B
40  EFAB         C
41  FABC         D

In [17]:
songString_2 = "ABCDEFIGHABCDEFIGHABCDEFIGHABCDEFIGHABCDEF"
df_2 = generate_note_dataframe(songString_2)
print(df_2)

    note next note
0   ABCD         E
1   BCDE         F
2   CDEF         I
3   DEFI         G
4   EFIG         H
5   FIGH         A
6   IGHA         B
7   GHAB         C
8   HABC         D
9   ABCD         E
10  BCDE         F
11  CDEF         I
12  DEFI         G
13  EFIG         H
14  FIGH         A
15  IGHA         B
16  GHAB         C
17  HABC         D
18  ABCD         E
19  BCDE         F
20  CDEF         I
21  DEFI         G
22  EFIG         H
23  FIGH         A
24  IGHA         B
25  GHAB         C
26  HABC         D
27  ABCD         E
28  BCDE         F
29  CDEF         I
30  DEFI         G
31  EFIG         H
32  FIGH         A
33  IGHA         B
34  GHAB         C
35  HABC         D
36  ABCD         E
37  BCDE         F
38  CDEF         A
39  DEFA         B
40  EFAB         C
41  FABC         D

In [5]:
# Define the song strings
song_strings = [
    "ABCDEFGHIABCDEFGHIABCDEFGHIABCDEFGHIABCDEF",  # normal
    "IHGFEDCBAIHGFEDCBAIHGFEDCBAIHGFEDCBAIHGFED",  # reverse
    "CCGGAAGFFEEDDCGGFFEEDGGFFEEDCCGGAAGFFEEDDC",  # daisy bells
    "ABCDEFIGHABCDEFIGHABCDEFIGHABCDEFIGHABCDEF",  # igh contradiction
    "ABCDAFGHIEBCDEAGHIAFCDEFIHIABADEFGCIABCBEF",  # 5th note different
    "AHCFEDGBIAHCFEDGBIAHCFEDGBIAHCFEDGBIAHCFED"   # every 2nd note different
]

# Dictionary to hold DataFrames
dataframes = {}

# Generate DataFrames for each song string
for i, song in enumerate(song_strings):
    df = generate_note_dataframe(song)
    dataframes[f'song_{i + 1}'] = df
    print(f"DataFrame for song {i + 1} created.")

# Optionally, print or inspect the DataFrames
for name, df in dataframes.items():
    print(f"\n{name} DataFrame:")
    print(df.head())  # Print only the first few rows for brevity

DataFrame for song 1 created.
DataFrame for song 2 created.
DataFrame for song 3 created.
DataFrame for song 4 created.
DataFrame for song 5 created.
DataFrame for song 6 created.

song_1 DataFrame:
   note next note
0  ABCD         E
1  BCDE         F
2  CDEF         G
3  DEFG         H
4  EFGH         I

song_2 DataFrame:
   note next note
0  IHGF         E
1  HGFE         D
2  GFED         C
3  FEDC         B
4  EDCB         A

song_3 DataFrame:
   note next note
0  CCGG         A
1  CGGA         A
2  GGAA         G
3  GAAG         F
4  AAGF         F

song_4 DataFrame:
   note next note
0  ABCD         E
1  BCDE         F
2  CDEF         I
3  DEFI         G
4  EFIG         H

song_5 DataFrame:
   note next note
0  ABCD         A
1  BCDA         F
2  CDAF         G
3  DAFG         H
4  AFGH         I

song_6 DataFrame:
   note next note
0  AHCF         E
1  HCFE         D
2  CFED         G
3  FEDG         B
4  EDGB         I

In [20]:
#CONTRADICTION
def create_comparison_matrix(df1, df2):
    # Ensure both dataframes have the expected number of rows
    assert len(df1) == 42 and len(df2) == 42, "Both dataframes should have 42 rows."
    
    # Initialize a 42x42 matrix of zeros
    matrix = np.zeros((42, 42), dtype=int)
    
    # Iterate over each row of the first dataframe
    for i in range(42):
        # Get the "note" and "next note" for the current row in df1
        note1 = df1.iloc[i]['note']
        next_note1 = df1.iloc[i]['next note']
        
        # Compare with each row in the second dataframe
        for j in range(42):
            # Get the "note" and "next note" for the current row in df2
            note2 = df2.iloc[j]['note']
            next_note2 = df2.iloc[j]['next note']
            
            # Check if notes match and next notes do not match
            if note1 == note2 and next_note1 != next_note2:
                matrix[i][j] = 1

    return matrix

# Example usage with hypothetical dataframes df1 and df2
# You would replace these dataframes with your actual data
df1 = generate_note_dataframe("ABCDEFGHIABCDEFGHIABCDEFGHIABCDEFGHIABCDEF")
df2 = generate_note_dataframe("ABCDEFGHIABCDEFGHIABCDEFGHIABCDEFGHIABCDEF")  # Replace with different string if needed
comparison_matrix = create_comparison_matrix(df1, df2)
print(comparison_matrix)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 1 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]

In [21]:
import pandas as pd

# Convert the numpy array to a DataFrame for better visualization
def display_matrix_as_dataframe(matrix):
    df = pd.DataFrame(matrix)
    with pd.option_context('display.max_rows', None, 'display.max_columns', None):
        print(df)

# Use the function to display your matrix
display_matrix_as_dataframe(comparison_matrix)

    0   1   2   3   4   5   6   7   8   9   10  11  12  13  14  15  16  17  \
0    0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
1    0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
2    0   0   1   0   0   0   0   0   0   0   0   1   0   0   0   0   0   0
3    0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
4    0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
5    0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
6    0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
7    0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
8    0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
9    0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
10   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
11   0   0   1   0   0   0   0   0   0   0   0   1   0   0   0   0   0   0
12   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
13   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
14   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
15   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
16   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
17   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
18   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
19   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
20   0   0   1   0   0   0   0   0   0   0   0   1   0   0   0   0   0   0
21   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
22   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
23   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
24   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
25   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
26   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
27   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
28   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
29   0   0   1   0   0   0   0   0   0   0   0   1   0   0   0   0   0   0
30   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
31   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
32   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
33   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
34   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
35   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
36   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
37   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
38   0   0   1   0   0   0   0   0   0   0   0   1   0   0   0   0   0   0
39   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
40   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
41   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0

    18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  \
0    0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
1    0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
2    0   0   1   0   0   0   0   0   0   0   0   1   0   0   0   0   0   0
3    0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
4    0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
5    0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
6    0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
7    0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
8    0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
9    0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
10   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
11   0   0   1   0   0   0   0   0   0   0   0   1   0   0   0   0   0   0
12   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
13   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
14   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
15   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
16   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
17   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
18   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
19   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
20   0   0   1   0   0   0   0   0   0   0   0   1   0   0   0   0   0   0
21   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
22   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
23   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
24   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
25   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
26   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
27   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
28   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
29   0   0   1   0   0   0   0   0   0   0   0   1   0   0   0   0   0   0
30   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
31   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
32   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
33   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
34   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
35   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
36   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
37   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
38   0   0   1   0   0   0   0   0   0   0   0   1   0   0   0   0   0   0
39   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
40   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
41   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0

    36  37  38  39  40  41
0    0   0   0   0   0   0
1    0   0   0   0   0   0
2    0   0   1   0   0   0
3    0   0   0   0   0   0
4    0   0   0   0   0   0
5    0   0   0   0   0   0
6    0   0   0   0   0   0
7    0   0   0   0   0   0
8    0   0   0   0   0   0
9    0   0   0   0   0   0
10   0   0   0   0   0   0
11   0   0   1   0   0   0
12   0   0   0   0   0   0
13   0   0   0   0   0   0
14   0   0   0   0   0   0
15   0   0   0   0   0   0
16   0   0   0   0   0   0
17   0   0   0   0   0   0
18   0   0   0   0   0   0
19   0   0   0   0   0   0
20   0   0   1   0   0   0
21   0   0   0   0   0   0
22   0   0   0   0   0   0
23   0   0   0   0   0   0
24   0   0   0   0   0   0
25   0   0   0   0   0   0
26   0   0   0   0   0   0
27   0   0   0   0   0   0
28   0   0   0   0   0   0
29   0   0   1   0   0   0
30   0   0   0   0   0   0
31   0   0   0   0   0   0
32   0   0   0   0   0   0
33   0   0   0   0   0   0
34   0   0   0   0   0   0
35   0   0   0   0   0   0
36   0   0   0   0   0   0
37   0   0   0   0   0   0
38   0   0   0   0   0   0
39   0   0   0   0   0   0
40   0   0   0   0   0   0
41   0   0   0   0   0   0

In [23]:
42*42

1764

In [22]:
# Assuming 'comparison_matrix' is your matrix
number_of_ones = np.sum(comparison_matrix)

print("Number of 1's in the matrix:", number_of_ones)

Number of 1's in the matrix: 24

In [26]:
import numpy as np
import pandas as pd
from itertools import combinations_with_replacement

# Generate DataFrames for each song string
song_strings = [
    "ABCDEFGHIABCDEFGHIABCDEFGHIABCDEFGHIABCDEF",  # normal
    "IHGFEDCBAIHGFEDCBAIHGFEDCBAIHGFEDCBAIHGFED",  # reverse
    "CCGGAAGFFEEDDCGGFFEEDGGFFEEDCCGGAAGFFEEDDC",  # daisy bells
    "ABCDEFIGHABCDEFIGHABCDEFIGHABCDEFIGHABCDEF",  # igh contradiction
    "ABCDAFGHIEBCDEAGHIAFCDEFIHIABADEFGCIABCBEF",  # 5th note different
    "AHCFEDGBIAHCFEDGBIAHCFEDGBIAHCFEDGBIAHCFED"   # every 2nd note different
]

dataframes = {f"song_{i + 1}": generate_note_dataframe(song) for i, song in enumerate(song_strings)}

# Dictionary to hold comparison matrices
comparison_matrices = {}

# Generate all combinations of dataframes and compute comparison matrices
for (name1, df1), (name2, df2) in combinations_with_replacement(dataframes.items(), 2):
    matrix = create_comparison_matrix(df1, df2)
    comparison_matrices[f'{name1}_vs_{name2}'] = matrix
    print(f"Matrix for {name1} vs {name2} created.")

# Calculate and display the sum of 1's in each matrix
sums_of_ones = {}
for name, matrix in comparison_matrices.items():
    sum_of_ones = np.sum(matrix)
    sums_of_ones[name] = sum_of_ones
    print(f"Number of 1's in {name} Comparison Matrix: {sum_of_ones}")

Matrix for song_1 vs song_1 created.
Matrix for song_1 vs song_2 created.
Matrix for song_1 vs song_3 created.
Matrix for song_1 vs song_4 created.
Matrix for song_1 vs song_5 created.
Matrix for song_1 vs song_6 created.
Matrix for song_2 vs song_2 created.
Matrix for song_2 vs song_3 created.
Matrix for song_2 vs song_4 created.
Matrix for song_2 vs song_5 created.
Matrix for song_2 vs song_6 created.
Matrix for song_3 vs song_3 created.
Matrix for song_3 vs song_4 created.
Matrix for song_3 vs song_5 created.
Matrix for song_3 vs song_6 created.
Matrix for song_4 vs song_4 created.
Matrix for song_4 vs song_5 created.
Matrix for song_4 vs song_6 created.
Matrix for song_5 vs song_5 created.
Matrix for song_5 vs song_6 created.
Matrix for song_6 vs song_6 created.
Number of 1's in song_1_vs_song_1 Comparison Matrix: 8
Number of 1's in song_1_vs_song_2 Comparison Matrix: 0
Number of 1's in song_1_vs_song_3 Comparison Matrix: 0
Number of 1's in song_1_vs_song_4 Comparison Matrix: 24
Number of 1's in song_1_vs_song_5 Comparison Matrix: 35
Number of 1's in song_1_vs_song_6 Comparison Matrix: 0
Number of 1's in song_2_vs_song_2 Comparison Matrix: 8
Number of 1's in song_2_vs_song_3 Comparison Matrix: 0
Number of 1's in song_2_vs_song_4 Comparison Matrix: 0
Number of 1's in song_2_vs_song_5 Comparison Matrix: 0
Number of 1's in song_2_vs_song_6 Comparison Matrix: 0
Number of 1's in song_3_vs_song_3 Comparison Matrix: 12
Number of 1's in song_3_vs_song_4 Comparison Matrix: 0
Number of 1's in song_3_vs_song_5 Comparison Matrix: 0
Number of 1's in song_3_vs_song_6 Comparison Matrix: 0
Number of 1's in song_4_vs_song_4 Comparison Matrix: 8
Number of 1's in song_4_vs_song_5 Comparison Matrix: 15
Number of 1's in song_4_vs_song_6 Comparison Matrix: 0
Number of 1's in song_5_vs_song_5 Comparison Matrix: 0
Number of 1's in song_5_vs_song_6 Comparison Matrix: 0
Number of 1's in song_6_vs_song_6 Comparison Matrix: 8

In [6]:
#OVERLAP
def create_comparison_matrix(df1, df2):
    # Ensure both dataframes have the expected number of rows
    assert len(df1) == 42 and len(df2) == 42, "Both dataframes should have 42 rows."
    
    # Initialize a 42x42 matrix of zeros
    matrix = np.zeros((42, 42), dtype=int)
    
    # Iterate over each row of the first dataframe
    for i in range(42):
        # Get the "note" and "next note" for the current row in df1
        note1 = df1.iloc[i]['note']
        next_note1 = df1.iloc[i]['next note']
        
        # Compare with each row in the second dataframe
        for j in range(42):
            # Get the "note" and "next note" for the current row in df2
            note2 = df2.iloc[j]['note']
            next_note2 = df2.iloc[j]['next note']
            
            # Check if notes match and next notes do not match
            if note1 == note2 and next_note1 == next_note2:
                matrix[i][j] = 1

    return matrix

# # Example usage with hypothetical dataframes df1 and df2
# # You would replace these dataframes with your actual data
# df1 = generate_note_dataframe("ABCDEFGHIABCDEFGHIABCDEFGHIABCDEFGHIABCDEF")
# df2 = generate_note_dataframe("ABCDEFGHIABCDEFGHIABCDEFGHIABCDEFGHIABCDEF")  # Replace with different string if needed
# comparison_matrix = create_comparison_matrix(df1, df2)
# print(comparison_matrix)

In [7]:
import numpy as np
import pandas as pd
from itertools import combinations_with_replacement

# Generate DataFrames for each song string
song_strings = [
    "ABCDEFGHIABCDEFGHIABCDEFGHIABCDEFGHIABCDEF",  # normal
    "IHGFEDCBAIHGFEDCBAIHGFEDCBAIHGFEDCBAIHGFED",  # reverse
    "CCGGAAGFFEEDDCGGFFEEDGGFFEEDCCGGAAGFFEEDDC",  # daisy bells
    "ABCDEFIGHABCDEFIGHABCDEFIGHABCDEFIGHABCDEF",  # igh contradiction
    "ABCDAFGHIEBCDEAGHIAFCDEFIHIABADEFGCIABCBEF",  # 5th note different
    "AHCFEDGBIAHCFEDGBIAHCFEDGBIAHCFEDGBIAHCFED"   # every 2nd note different
]

dataframes = {f"song_{i + 1}": generate_note_dataframe(song) for i, song in enumerate(song_strings)}

# Dictionary to hold comparison matrices
comparison_matrices = {}

# Generate all combinations of dataframes and compute comparison matrices
for (name1, df1), (name2, df2) in combinations_with_replacement(dataframes.items(), 2):
    matrix = create_comparison_matrix(df1, df2)
    comparison_matrices[f'{name1}_vs_{name2}'] = matrix
    print(f"Matrix for {name1} vs {name2} created.")

# Calculate and display the sum of 1's in each matrix
sums_of_ones = {}
for name, matrix in comparison_matrices.items():
    sum_of_ones = np.sum(matrix)
    sums_of_ones[name] = sum_of_ones
    print(f"Number of 1's in {name} Comparison Matrix: {sum_of_ones}")

Matrix for song_1 vs song_1 created.
Matrix for song_1 vs song_2 created.
Matrix for song_1 vs song_3 created.
Matrix for song_1 vs song_4 created.
Matrix for song_1 vs song_5 created.
Matrix for song_1 vs song_6 created.
Matrix for song_2 vs song_2 created.
Matrix for song_2 vs song_3 created.
Matrix for song_2 vs song_4 created.
Matrix for song_2 vs song_5 created.
Matrix for song_2 vs song_6 created.
Matrix for song_3 vs song_3 created.
Matrix for song_3 vs song_4 created.
Matrix for song_3 vs song_5 created.
Matrix for song_3 vs song_6 created.
Matrix for song_4 vs song_4 created.
Matrix for song_4 vs song_5 created.
Matrix for song_4 vs song_6 created.
Matrix for song_5 vs song_5 created.
Matrix for song_5 vs song_6 created.
Matrix for song_6 vs song_6 created.
Number of 1's in song_1_vs_song_1 Comparison Matrix: 166
Number of 1's in song_1_vs_song_2 Comparison Matrix: 0
Number of 1's in song_1_vs_song_3 Comparison Matrix: 0
Number of 1's in song_1_vs_song_4 Comparison Matrix: 54
Number of 1's in song_1_vs_song_5 Comparison Matrix: 2
Number of 1's in song_1_vs_song_6 Comparison Matrix: 0
Number of 1's in song_2_vs_song_2 Comparison Matrix: 166
Number of 1's in song_2_vs_song_3 Comparison Matrix: 0
Number of 1's in song_2_vs_song_4 Comparison Matrix: 0
Number of 1's in song_2_vs_song_5 Comparison Matrix: 0
Number of 1's in song_2_vs_song_6 Comparison Matrix: 0
Number of 1's in song_3_vs_song_3 Comparison Matrix: 84
Number of 1's in song_3_vs_song_4 Comparison Matrix: 0
Number of 1's in song_3_vs_song_5 Comparison Matrix: 0
Number of 1's in song_3_vs_song_6 Comparison Matrix: 0
Number of 1's in song_4_vs_song_4 Comparison Matrix: 166
Number of 1's in song_4_vs_song_5 Comparison Matrix: 6
Number of 1's in song_4_vs_song_6 Comparison Matrix: 0
Number of 1's in song_5_vs_song_5 Comparison Matrix: 42
Number of 1's in song_5_vs_song_6 Comparison Matrix: 0
Number of 1's in song_6_vs_song_6 Comparison Matrix: 166

In [27]:
# Original song pattern
original_song = "ABCDEF"

# Introduce variations after matching sequences
varied_song = "ABCDEG ABCEFG ABCDFG ABCDEH"

# Generate DataFrames for the original and varied song
df_original = generate_note_dataframe(original_song * 8)  # Repeat to fit length
df_varied = generate_note_dataframe(varied_song * 8)

# Compare and print the new matrix
new_matrix = create_comparison_matrix(df_original, df_varied)
print("New Comparison Matrix:\n", new_matrix)
print("Number of 1's in the new matrix:", np.sum(new_matrix))

New Comparison Matrix:
 [[0 0 0 ... 0 0 1]
 [0 1 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
Number of 1's in the new matrix: 35

In [29]:
df_original

    note next note
0   ABCD         E
1   BCDE         F
2   CDEF         A
3   DEFA         B
4   EFAB         C
5   FABC         D
6   ABCD         E
7   BCDE         F
8   CDEF         A
9   DEFA         B
10  EFAB         C
11  FABC         D
12  ABCD         E
13  BCDE         F
14  CDEF         A
15  DEFA         B
16  EFAB         C
17  FABC         D
18  ABCD         E
19  BCDE         F
20  CDEF         A
21  DEFA         B
22  EFAB         C
23  FABC         D
24  ABCD         E
25  BCDE         F
26  CDEF         A
27  DEFA         B
28  EFAB         C
29  FABC         D
30  ABCD         E
31  BCDE         F
32  CDEF         A
33  DEFA         B
34  EFAB         C
35  FABC         D
36  ABCD         E
37  BCDE         F
38  CDEF         A
39  DEFA         B
40  EFAB         C
41  FABC         D

In [28]:
df_varied

    note next note
0   ABCD         E
1   BCDE         G
2   CDEG
3   DEG          A
4   EG A         B
5   G AB         C
6    ABC         E
7   ABCE         F
8   BCEF         G
9   CEFG
10  EFG          A
11  FG A         B
12  G AB         C
13   ABC         D
14  ABCD         F
15  BCDF         G
16  CDFG
17  DFG          A
18  FG A         B
19  G AB         C
20   ABC         D
21  ABCD         E
22  BCDE         H
23  CDEH         A
24  DEHA         B
25  EHAB         C
26  HABC         D
27  ABCD         E
28  BCDE         G
29  CDEG
30  DEG          A
31  EG A         B
32  G AB         C
33   ABC         E
34  ABCE         F
35  BCEF         G
36  CEFG
37  EFG          A
38  FG A         B
39  G AB         C
40   ABC         D
41  ABCD         F